'use strict';
window.UniversityReviewNotes = {
  year: 2027,
  reviewedAt: '2026-09-13',
  schools: {
    11: {
      status: "명칭·비율 확인",
      kind: "reviewed",
      summary: "스포츠산업경영학과로 명칭 정정. 가군20명, 수능40·학생부20·실기40 확인.",
      followUp: "체육대학 광역단위 수시이월 모집은 별도 신규등록하지 않았습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.kookmin.ac.kr/onschedule/application.php"}],
    },
    14: {
      status: "중복 모집단위 정리",
      kind: "reviewed",
      summary: "해양스포츠학과의 중복 항목을 정리했습니다. 가군 1명, 수능 60%·실기 40%입니다.",
      followUp: "",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.mmu.ac.kr/admission/contents/lastRegular"}],
    },
    19: {
      status: "2027 요강 반영 · 환산표 임시 적용",
      kind: "provisional",
      summary: "가군 28명, 수능 700점·실기 300점입니다. 한국사 감점에는 수능 반영비율 70%를 적용합니다.",
      followUp: "영어·탐구는 2026 공식 환산표를 임시 적용하며, 2027 환산표 발표 후 갱신합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.skku.edu/admission/html/regular/noticeView.html?idx=59515"}],
    },
    20: {
      status: "기존 실기 배점 유지",
      kind: "owner-confirmed",
      summary: "스포츠레저 실기 만점은 200점입니다. 배점 변경이 없다는 사용자 확인에 따라 기존 표를 유지합니다.",
      followUp: "2027 상세 배점표 원문을 새로 확보해 검수한 상태는 아닙니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.sungshin.ac.kr/guide/dataroom.htm?bbsid=notice&ctg_cd=common&page=8&skey=&keyword=&mode=view&bltn_seq=36371"}],
    },
    21: {
      status: "기존 실기 배점 유지",
      kind: "owner-confirmed",
      summary: "운동재활 실기 만점은 200점입니다. 배점 변경이 없다는 사용자 확인에 따라 기존 표를 유지합니다.",
      followUp: "2027 상세 배점표 원문을 새로 확보해 검수한 상태는 아닙니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.sungshin.ac.kr/guide/dataroom.htm?bbsid=notice&ctg_cd=common&page=8&skey=&keyword=&mode=view&bltn_seq=36371"}],
    },
    22: {
      status: "수능 정정 · 탐구표 임시 적용",
      kind: "provisional",
      summary: "수능 900점·실기 100점입니다. 실제 국어·수학 표준점수와 탐구 2과목 변환점수 평균을 반영하고 환산 후 한국사를 감점합니다.",
      followUp: "탐구는 2026 공식 변환표를 임시 적용하며, 2027 변환표 발표 후 갱신합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.yonsei.ac.kr/seoul/upload/guide/20260901184445WSGU8N.PDF"}],
    },
    25: {
      status: "수능 산식·총점 정정 · 배구 경계 임시 적용",
      kind: "provisional",
      summary: "2026.9.8 개정된2027 공식요강을 재확인했습니다. 배구 남26회·여24회의 원문 경계 중복은 여전히 있어 상담용87점을 유지합니다. 수능은 국수 표준점수 상위1+탐구 (표준점수+백분위)/2 상위1+영어·한국사로 정정했습니다. 명목 수능400+실기300=700점이며 나머지 실기는 앞선 검수 결과를 유지합니다.",
      followUp: "배구 남자 26회·여자 24회의 경계 중복은 상담용 87점을 유지하며 공식 확인이 남아 있습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.wku.ac.kr/submenu.do?menuurl=pNIJTWxI%2b8B8m%2bUBBAchHA%3d%3d&"}],
    },
    27: {
      status: "2종목 유지 · 배점 추후 수정",
      kind: "provisional",
      summary: "2027 정시요강 재확인: 스포츠과학부 수능40%·실기60%, 제멀·20m왕복 두종목600점. 중간 급간은 상담용 임시표이며 별도 상세 채점기준 확인이 필요합니다.",
      followUp: "중간 급간은 상담용 임시표입니다. 2027 정시 상세 배점표 확인 후 갱신합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://sports.inu.ac.kr/bbs/board.php?bo_table=sub1_3&wr_id=12"}],
    },
    28: {
      status: "작년 실기표 임시 적용",
      kind: "provisional",
      summary: "2027 정시요강 재확인: 스포츠의학부 수능60%·실기40%, 실기400점. 종목별 기록 배점은 기존2026표 임시 적용이며 별도 상세 채점기준 확인이 필요합니다.",
      followUp: "2027 상세 배점표 확보 후 갱신합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.inu.ac.kr/submenu.do?menuurl=69HsiUDd88Yz%2F6q8AbV4%2BA%3D%3D&"}],
    },
    29: {
      status: "작년 실기표 임시 적용",
      kind: "provisional",
      summary: "2027 정시요강 재확인: 체육교육과 수능50%·실기50%, 실기500점. 종목별 기록 배점은 기존2026표 임시 적용이며 별도 상세 채점기준 확인이 필요합니다.",
      followUp: "2027 상세 배점표 확보 후 갱신합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.inu.ac.kr/submenu.do?menuurl=69HsiUDd88Yz%2F6q8AbV4%2BA%3D%3D&"}],
    },
    31: {
      status: "공식 산식·실기표 반영",
      kind: "reviewed",
      summary: "수능 800점·실기 1,200점입니다. 윗몸일으키기 30점·제자리멀리뛰기 35점·Z자달리기 35점의 합에 12를 곱하며, 한국사는 별도 가산합니다.",
      followUp: "수시이월 모집입니다. Z자달리기 표의 마지막 구간보다 느린 기록은 공식 점수 확인이 남아 있습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://i.chosun.ac.kr/main/menu?gc=1069DIBH"}],
    },
    32: {
      status: "통합모집·실기표 반영",
      kind: "reviewed",
      summary: "라이프케어 일반실기 모집으로 반영했습니다. 수능 800점·실기 1,200점이며 공식 실기 급간을 적용합니다.",
      followUp: "수시이월 모집입니다. 한국사는 별도 가산하며, Z자달리기 표 범위 밖 기록은 공식 점수 확인이 남아 있습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://i.chosun.ac.kr/main/menu?gc=1069DIBH"}],
    },
    33: {
      status: "명칭·비실기 산식 정정",
      kind: "reviewed",
      summary: "스포츠재활복지학전공 가군 수시이월·수능100%. 국수영 상위2와 탐구/한국사 상위1을 고르고 영역별 소수점을 버립니다.",
      followUp: "스포츠건강관리는 별도 모집단위입니다. 최종 수시이월 인원은 추후 확인합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.joongbu.ac.kr/board.es?mid=a60501000000&bid=0232&list_no=346204&act=view"}],
    },
    34: {
      status: "수능우수자 산식 정정",
      kind: "reviewed",
      summary: "가군2명·수능100%, 실기·면접없음. 국수영 상위2와 탐구/한국사 상위1의 영역별 버림을 반영했습니다.",
      followUp: "명시된 수능우수자 전형 기준입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.joongbu.ac.kr/board.es?mid=a60501000000&bid=0232&list_no=346204&act=view"}],
    },
    36: {
      status: "공식 배점·체조 점수 반영",
      kind: "reviewed",
      summary: "총점 500점은 수능 300점과 실기 200점의 합입니다. 핸드볼·기계체조 각 100점이며, 체조는 학교가 제공한 45~100점 숫자를 합산합니다.",
      followUp: "20m왕복달리기는 실기에서 제외했습니다. 체조 점수는 등급으로 다시 환산하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.cnu.ac.kr/_prog/_board/?mode=V&no=2026419&code=notice_faculty&site_dvs_cd=uadm&menu_dvs_cd=0101"}],
    },
    70: {
      status: "수능·실기 산식 정정",
      kind: "reviewed",
      summary: "수능200·실기800. 실기는400+(3종목 평균×4), 수능은 기본100+국수영 상위2+탐구 우수1입니다.",
      followUp: "메디신볼 최저경계 아래 숫자와 일부 소수처리 문구의 확인이 남습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.hoseo.ac.kr/submenu.do?menuurl=69HsiUDd88Yz%2f6q8AbV4%2bA%3d%3d&"}],
    },
    71: {
      status: "작년 실기표·기존 계산 유지",
      kind: "provisional",
      summary: "2027 서울캠퍼스 정시요강 재확인: 나군25명, 수능600+실기400, 왕복·높이뛰기·핸드스프링·농구·윗몸5종목. 기록별 상세표가 없어 기존2026표를 임시 적용합니다. GLOCAL 골프 자료와 구분합니다.",
      followUp: "2027 상세 배점표를 기다리고 있습니다. 핸드스프링 F는 표 40점과 기존 계산 45점의 차이가 있어 확인이 필요합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.konkuk.ac.kr/admission/37869/subview.do"}],
    },
    74: {
      status: "인원·영어·한국사 정정",
      kind: "reviewed",
      summary: "나군44명, 수능60·실기40점. 영어30%와 국수탐 상위2 각35%, 탐구 우수1 및 공식84급간을 확인했습니다.",
      followUp: "수시이월 전 인원입니다. 영어·한국사 등급표도2027 기준으로 정정했습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://enter.kyonggi.ac.kr/cms/FR_BBS_CON/BoardView.do?MENU_ID=280&CONTENTS_NO=3&SITE_NO=2&BOARD_SEQ=3&BBS_SEQ=4057"}],
    },
    75: {
      status: "실기 폐지·수능 산식 정정",
      kind: "reviewed",
      summary: "다군 수시이월·수능100점·비실기. 국35·수30·영20·탐구 우수1 15%를 반영합니다.",
      followUp: "최종 수시이월 인원은 추후 확인합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://enter.kyonggi.ac.kr/cms/FR_BBS_CON/BoardView.do?MENU_ID=280&CONTENTS_NO=3&SITE_NO=2&BOARD_SEQ=3&BBS_SEQ=4057"}],
    },
    85: {
      status: "스포츠과학부 통합모집",
      kind: "reviewed",
      summary: "다군 7명, 수능 400점·실기 600점입니다. 국어·수학·영어·탐구 상위 2영역과 한국사 가산점을 반영하며 수능 400점 상한을 적용합니다.",
      followUp: "제자리멀리뛰기·20m왕복달리기는 각 300점입니다. 과거 상담 저장점수는 자동 재계산하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.dju.ac.kr/enter/html/regular/guide.asp"}],
    },
    86: {
      status: "농어촌 통합·수능100%",
      kind: "reviewed",
      summary: "다군 수시이월·수능1000점·비실기. 국수영탐 상위2와 한국사 가산 후1000점 상한을 적용합니다.",
      followUp: "최종 수시이월 인원은 추후 확인합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.dju.ac.kr/enter/html/regular/guide.asp"}],
    },
    87: {
      status: "체육실기전형·환산점수 반영",
      kind: "reviewed",
      summary: "나군 23명, 수능 400점·실기 600점입니다. 실기 4종목 각 25점의 합에 6을 곱해 600점으로 환산하며, 한국사는 최대 4점 별도 가산합니다.",
      followUp: "종목별 2회 실격·응시 포기의 최종 결과는 실격으로 입력하면 0점입니다. 단독 F·파울을 최종 실격으로 간주하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://enter.duksung.ac.kr/upload_data/mojib/20260901130207_80.pdf"}],
    },
    96: {
      status: "1단계 수능 확인 · 2단계 대기",
      kind: "provisional",
      summary: "2027 정시 요강 31~32쪽 확인: 1단계 수능은 국어+수학×1.2+탐구2과목합×0.8에서 영어·한국사를 감점합니다. 2단계 수능은 1단계 합격자 최고·최저점이 필요합니다. 실기 원점수100점·최종반영20점, 상세 안내는 2026.10.12 이후입니다. 기존 상담 계산은 최종 전형총점이 아닙니다.",
      followUp: "실기 세부 안내는 2026년 10월 12일 이후 발표 예정입니다. 2단계 환산에는 합격자 최고·최저점이 필요합니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://admission.snu.ac.kr/webdata/admission/files/2027jungsi.pdf"}],
      withholdTotal: true,
      withholdReason: "2단계 환산 전 · 최종총점 미확정",
      practicalDisplay: "원점수 100점 → 최종 20점",
    },
    102: {
      status: "실기 66급간 확인 · 하위급간 임시 적용",
      kind: "provisional",
      summary: "2027 별첨 실기요강의 남녀100~50점66급간 확인. 제멀 정수cm·메디신0.1m·20m왕복0.01초로 절사하며 최종실격은 해당 종목0점. 원문에 없는45~25점30급간은 기존표 임시 적용이며 최신 확정값이 아닙니다.",
      followUp: "100~50점은 2027 별첨 확인, 45~25점은 원문에 없어 기존표를 임시 적용합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.sejong.ac.kr/ipsi/regular/notice.do?mode=view&articleNo=2779"},{"title":"2027 별첨 실기요강 · 체육 13쪽","url":"https://ipsi.sejong.ac.kr/ipsi/regular/notice.do?articleNo=2779&attachNo=2884&mode=download"}],
    },
    103: {
      status: "기초체력 모집인원 정정",
      kind: "reviewed",
      summary: "기초체력 모집은 20명입니다. 학부 전체 60명은 기초체력 20명과 전공실기 40명을 합친 수치입니다.",
      followUp: "",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.suwon.ac.kr/upload_data/guide/1787709757_5772.pdf"}],
    },
    104: {
      status: "전공실기 40명 · 객관실기 부분계산",
      kind: "partial",
      summary: "전공실기는 축구·농구·체조 중 택1로 공동 40명을 모집합니다. 제자리멀리뛰기 150점·지그재그런 150점을 계산하고, 전공실기 300점은 주관평가로 제외합니다.",
      followUp: "수능과 객관실기 소계까지만 산출합니다. 주관평가를 포함한 최종총점은 산출하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.suwon.ac.kr/upload_data/guide/1787709757_5772.pdf"}],
    },
    105: {
      status: "높이뛰기만 객관실기 계산",
      kind: "partial",
      summary: "높이뛰기 75점만 계산합니다. 허들 75점·체조 150점·선택실기 100점은 주관평가로 제외하며, 선택 종목은 축구·농구·배구·핸드볼입니다.",
      followUp: "높이뛰기 F는 110cm 실패로 50점입니다. 미응시는 0점이며 불합격 대상입니다. 주관평가를 포함한 최종총점은 산출하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.sookmyung.ac.kr/upload/BBS0021/20260901143304EF2RTS.PDF"}],
    },
    111: {
      status: "실기 54점 경계 확인 중",
      kind: "provisional",
      summary: "2027 공식 PDF 재확인: 수능350+실기150, 나군13명. 남자 제자리멀리뛰기54점 칸에 261이상/269이상 중복이 남아 있어 기존 상담용 261이상269미만을 유지합니다. 해당 급간은 공식 정정 확인 전 임시값입니다.",
      followUp: "남자 제멀 54점의 원문 중복은 공식 정정 확인이 남아 있습니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://ipsi.yongin.ac.kr/ipsi/guide/jungsi/mo_jungsi_20260902_0858.pdf"}],
    },
    114: {
      status: "수능 확인 · 실기·탐구표 임시 적용",
      kind: "provisional",
      summary: "2027 정시 요강 재확인: 나군30명, 1단계4배수, 수능600점에 영어 최대5점 별도가산·실기400점. 실기는 10m2회왕복·제멀·메디신2kg이며 기록별 상세표와 2027 탐구변환표 발표 확인이 필요합니다. 기존 실기표는 최신 확정표가 아닙니다.",
      followUp: "2027 실기 상세 배점표와 수능 이후 발표할 탐구변환표를 확인해야 합니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://admission.ewha.ac.kr/upload/GUIDES/20260901162227VPFXS9.pdf"}],
    },
    115: {
      status: "수능 환산·체조·축구 감점 정정",
      kind: "reviewed",
      summary: "2027 공식 실기: 100m·지그재그·체조택1·축구 각100점 원점수를 합하여 ×0.5, 만점200점입니다. 체조 동작·A/B/C 등급과 축구 골인 성공/실패를 선택합니다. 정상 축구 골 실패는 원점수10점(환산5점) 감점합니다. 수능은 과목별 표준점수÷전국최고점으로 환산하고 10자리·4자리 절사와 최종3자리 반올림 후 한국사를 가산합니다. 수시이월 모집입니다.",
      followUp: "수능 최고표점은 선택한 시험 기준입니다. 최종 수시이월 인원은 추후 확인합니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://admission.jnu.ac.kr/Data/tmfiles/admission/doc/2027/2027-jung-260828.pdf"}],
    },
    131: {
      status: "골프 12회 객관평가 부분계산",
      kind: "partial",
      summary: "2027 GLOCAL 골프: 드라이버·3번우드·아이언·어프로치 각3회, A30/B20/C10/D0의 객관평가12회를 합하여 최대360점만 계산합니다. 주관평가340점은 입력·계산에서 제외하고 최종실기·전형총점은 산출하지 않습니다. 수시이월 모집입니다.",
      followUp: "주관평가 340점을 포함한 최종실기·전형총점은 산출하지 않습니다. 최종 수시이월 인원은 추후 확인합니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://enter.kku.ac.kr/upload_data/mojib/20260901154238_44.pdf"}],
    },
    143: {
      status: "전형 확인 · 실기 환산식 확인 중",
      kind: "provisional",
      summary: "2027 정시 요강 재확인: 다군38명, 수능600+실기400. 농구는 드리블과 골밑슛을 포함한 하나의 시간 기록이며 제자리멀리뛰기와 함께2종목입니다. 요강에 상세 배점·선형환산식이 없어 기존 상담용 실기 계산의 최신 여부는 미확정입니다.",
      followUp: "농구와 제멀의 상세 환산표·선형 산식이 원문에 없어 기존 상담 계산을 임시 유지합니다.",
      sources: [{"title":"2027 공식 모집요강","url":"https://iphak.mju.ac.kr/_common/new_download_file.php?menu=boardfile&file_no=10782"}],
    },
    150: {
      status: "예체능 통합모집·수능 산식 반영",
      kind: "reviewed",
      summary: "사회체육학전공을 포함한 예체능분야 다군 수시이월 모집입니다. 수능 명목 300점이며, 국어·영어 필수와 수학·탐구 중 상위 1영역을 반영합니다. 미적분·기하는 선택 비교 전에 5점을 가산합니다.",
      followUp: "사회체육학전공 배정을 보장하지 않습니다. 최종 수시이월 인원은 추후 확인해야 합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.scnu.ac.kr/iphak/na/ntt/selectNttInfo.do?nttSn=281319433&mi=1676"}],
    },
    153: {
      status: "공동모집·비실기 전환",
      kind: "reviewed",
      summary: "스포츠의학·스마트헬스라이프전공 공동모집으로 다군 16명입니다. 수능 100%·비실기이며 환산점수는 800~1,000점입니다.",
      followUp: "16명은 스포츠의학 단독 인원이 아닌 공동모집 인원입니다. 수시이월 전 기준입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.sch.ac.kr/main.do"}],
    },
    155: {
      status: "모집인원·실기 환산 안내",
      kind: "reviewed",
      summary: "스포츠과학과는 나군 7명, 수능 40점·실기 60점입니다. 실기 2종목 각 100점의 합에 0.3을 곱해 60점으로 환산합니다. 스포츠계열자율전공은 2027 모집에서 폐지됐습니다.",
      followUp: "2회 파울의 기본점수 수치가 원문에 명시되지 않아 기존 상담 처리를 유지하며 확인이 필요합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://enter.anyang.ac.kr/10000018?detail=126"}],
    },
    168: {
      status: "실기 급간·총점 300점 반영",
      kind: "reviewed",
      summary: "춘천 스포츠과학과는 수능 180점·실기 120점입니다. 남자 제자리멀리뛰기와 남녀 윗몸일으키기 기준을 정정했으며 탐구는 2과목 평균으로 반영합니다.",
      followUp: "모집인원은 수시이월 전 기준입니다. 과거 상담 저장점수·컷은 자동 재계산하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.kangwon.ac.kr/admission/extn/1468/ipsiGuide-usr/list.do?searchCl1=2"}],
    },
    170: {
      status: "WISE 수능·실기 기준 반영",
      kind: "reviewed",
      summary: "가군 15명, 수능 300점·실기 700점입니다. 영어를 포함한 상위 2영역을 반영하며 영어 1등급 환산점수는 98점입니다.",
      followUp: "최종 실격 종목은 0점입니다. 미응시는 실기 0점이며 불합격 대상입니다. 서울캠퍼스 체육교육과와 다른 모집단위입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.dongguk.ac.kr/article/notice/detail/111767"}],
    },
    171: {
      status: "WISE 모집인원·산식 반영",
      kind: "reviewed",
      summary: "가군 3명, 수능 300점·실기 700점입니다. 영어를 포함한 상위 2영역을 반영합니다.",
      followUp: "최종 실격 종목은 0점입니다. 미응시는 실기 0점이며 불합격 대상입니다. 모집인원은 수시이월 전 기준입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.dongguk.ac.kr/article/notice/detail/111767"}],
    },
    173: {
      status: "작년 실기표 임시 적용",
      kind: "provisional",
      summary: "2027 정시요강은 해양스포츠학과 명칭으로 모집하며 지그재그·윗몸·100m 각100점(최저72점), 악천후에는100m를10m왕복으로 대체합니다. 상세 급간은 기존2026표 임시 적용이며 원문과 운영 학과명 대응 확인이 남아 있습니다.",
      followUp: "2027 상세표와 모집요강의 해양스포츠학과·현재 표시된 해양스포츠전공 명칭 차이를 확인해야 합니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://iphak.pknu.ac.kr/pknu/board/board.htm?bbsid=notice&ctg_cd=ra&mode=view&code=iphak_help&bltn_seq=1211"}],
    },
    176: {
      status: "실기 세부요강 12월 발표 대기",
      kind: "provisional",
      summary: "2027 정시요강 재확인: 수능600+실기400, 60m달리기·제멀 각200점. 악천후60m대체는 지그재그. 상세 체육실기요강은2026년12월 홈페이지 공지 예정이며 기존2026표를 임시 적용합니다.",
      followUp: "2026년 12월 체육실기고사 세부요강 발표 예정입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.kmou.ac.kr/ipsi/na/ntt/selectNttInfo.do?nttSn=10378433&mi=3326"}],
    },
    179: {
      status: "모집인원·총점 400점 반영",
      kind: "reviewed",
      summary: "춘천 체육교육과는 나군 5명, 수능 300점·실기 100점입니다. 제자리멀리뛰기·윗몸일으키기 하위 배점을 정정했습니다.",
      followUp: "모집인원은 수시이월 전 기준입니다. 과거 상담 저장점수·컷은 자동 재계산하지 않습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.kangwon.ac.kr/admission/extn/1468/ipsiGuide-usr/list.do?searchCl1=2"}],
    },
    180: {
      status: "삼척 총점 300점·탐구평균 반영",
      kind: "reviewed",
      summary: "삼척 휴먼스포츠학과는 나군 3명, 수능 120점·실기 180점입니다. 탐구는 2과목 평균으로 반영합니다.",
      followUp: "춘천 스포츠과학과와 다른 모집단위입니다. 모집인원은 수시이월 전 기준입니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://admission.kangwon.ac.kr/admission/extn/1468/ipsiGuide-usr/list.do?searchCl1=2"}],
    },
    195: {
      status: "모집군 확인 · 환산 단위 확인 중",
      kind: "needs-confirmation",
      summary: "가군 5명·수능 100%·비실기는 2027 모집요강과 일치합니다.",
      followUp: "모집요강, 공식 계산기, 현재 상담 계산의 점수 단위가 달라 환산 단위를 확인 중입니다. 수능 점수·컷 비교에 주의해 주세요.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://www.gokmu.ac.kr/guide/board.htm?bbsid=notice&mode=view&bltn_seq=85544&etc1=common"}],
      withholdTotal: true,
    },
    204: {
      status: "스포츠과학과 신설 반영",
      kind: "reviewed",
      summary: "나군 15명 신설 모집단위입니다. 수능 200점·실기 800점이며, 실기는 메디신볼·20m왕복달리기·수직점프를 반영합니다.",
      followUp: "이전 골프산업학과와 다른 모집단위입니다. 일부 최저 기록 경계는 공식 확인이 남아 있습니다.",
      sources: [{"title":"공식 모집요강·입학안내","url":"https://ipsi.hoseo.ac.kr/submenu.do?menuurl=69HsiUDd88Yz%2f6q8AbV4%2bA%3d%3d&"}],
    },
  },
};
